### ISSUE TITLE
Is there a way i can use 

### ISSUE THREAD

**Issue by Nagatochyan** [Sraq-Zit/gfile#1]
is there a way i can use by module

**Comment by Sraq-Zit** [comment]
I changed the code so you can use it as a module as well
Reinstall it and check out the readme to know how to use it
let me know if something doesn't work

**Comment by Nagatochyan** [comment]
Thank you!!!!

**Comment by Sraq-Zit** [comment]
こちらこそ

**Comment by Nagatochyan** [comment]
日本語話せるんですか

**Comment by Sraq-Zit** [comment]
日常会話程度でなら、はい
