### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by reizhi** [Sraq-Zit/gfile#2]
Upload failed after a short period of time.
```
{'status': 104, 'message': '保存先ディレクトリを取得できませんでした。Cookieが無効になっている可能性があります 。'}
Traceback (most recent call last):
  File "/usr/local/bin/gfile", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/gfile/cmd.py", line 35, in main
    print(gf.upload().get_download_page())
  File "/usr/local/lib/python3.9/dist-packages/gfile/gfile.py", line 118, in upload
    if 'url' not in self.data:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by AtlasSonic** [comment]
Honestly, I made this repo just for personal use so it needs some fixes Ive been busy to do.
This usually happens when you upload a large file try adding `-n 1`
like this `gfile -n 1 upload https://gigefile...`

**Comment by Sraq-Zit** [comment]
I initially made this just for personal use so it really needs some fixes I have been busy to do.
This error usually occurs when uploading large files. try adding `-n 1` like this:
`gfile -n 1 upload /path/to/file`

**Comment by reizhi** [comment]
Thanks for your contribution. It won't work.

**Comment by Sraq-Zit** [comment]
Did you get the same error ?
What is the size of the file ?

**Comment by reizhi** [comment]
Yes, still the same error.
The file size is 921M, the error occurred at around 21%.

**Comment by reizhi** [comment]
This specific file can be successfully uploaded by setting `-n` with 5 or greater.

**Comment by Sraq-Zit** [comment]
I see, not sure why  but I guess there is a problem with indexing chunks of the file for the upload.
Anyway, I will try to enhance this once i get time
